--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

nightsister_rare = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "nightsister_bicep_r", weight = 2500000},
		{itemTemplate = "nightsister_vibro_unit", weight = 2500000},
		{itemTemplate = "nge_jedi_house_scheme", weight = 2500000},
		{itemTemplate = "nge_sith_house_scheme", weight = 2500000}
	}
}

addLootGroupTemplate("nightsister_rare", nightsister_rare)
