--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

nightsister_rare = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "nightsister_bicep_r", weight = 4000000},
		{itemTemplate = "nightsister_vibro_unit", weight = 6000000}
	}
}

addLootGroupTemplate("nightsister_rare", nightsister_rare)
