--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

agitator_motor_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/agitator_motor_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("agitator_motor_schematic", agitator_motor_schematic)