--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

be_poster = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_bioengineer_orange.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("be_poster", be_poster)