--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

bh_armor_gloves = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/wearables/armor/bounty_hunter/armor_bounty_hunter_gloves.iff",
	craftingValues = {
		{"armor_integrity",45000,45000,0},
		{"armor_rating",1,1,0},
		{"armor_effectiveness",60,60,0},
		{"armor_health_encumbrance",1,1,0},
		{"armor_action_encumbrance",1,1,0},
		{"armor_mind_encumbrance",1,1,0},
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("bh_armor_gloves", bh_armor_gloves)