--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

black_sun_razor = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/weapon/melee/special/blacksun_razor.iff",
	craftingValues = {
		{"mindamage",75,90,0},
		{"maxdamage",138,215,0},
		{"attackspeed",3.6,2.5,1},
		{"woundchance",14,26,0},
		{"hitpoints",1500,1700,0},
		{"zerorangemod",5,15,0},
		{"maxrangemod",5,15,0},
		{"midrange",3,3,0},
		{"midrangemod",5,15,0},
		{"maxrange",7,7,0},
		{"attackhealthcost",36,18,0},
		{"attackactioncost",54,30,0},
		{"attackmindcost",36,18,0},
	},
	customizationStringNames = {},
	customizationValues = {},
	
	-- randomDotChance: The chance of this weapon object dropping with a random dot on it. Higher number means less chance. Set to 0 to always have a random dot.
	randomDotChance = 30
	
}

addLootItemTemplate("black_sun_razor", black_sun_razor)
