--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

blank_canvas = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/flat_canvas.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("blank_canvas", blank_canvas)