--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

blue_wiring = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/wiring_blue.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("blue_wiring", blue_wiring)