--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

broken_viewscreen_grey = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/tool/viewscreen_broken_s2.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("broken_viewscreen_grey", broken_viewscreen_grey)