--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

broken_binoculars_s2 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/tool/binoculars_broken_s2.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("broken_binoculars_s2", broken_binoculars_s2)