--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

cantina_chair_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/cantina_chair_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("cantina_chair_schematic", cantina_chair_schematic)