--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

cargo_pocket = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/container/general/cargo_pocket.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("cargo_pocket", cargo_pocket)