--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

carved_bowl_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/bowl_carved_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("carved_bowl_schematic", carved_bowl_schematic)