--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

cheap_copper_battery = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/battery_cheap_copper.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("cheap_copper_battery", cheap_copper_battery)