--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

chemical_recycler_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/chemical_recycler_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("chemical_recycler_schematic", chemical_recycler_schematic)