--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

closed_basket_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/basket_closed_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("closed_basket_schematic", closed_basket_schematic)