--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

couch_blue_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/couch_blue_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("couch_blue_schematic", couch_blue_schematic)