--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

creature_recycler_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/creature_recycler_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("creature_recycler_schematic", creature_recycler_schematic)