--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

defensive_stance_poster = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_teras_kasi_2.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("defensive_stance_poster", defensive_stance_poster)