--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

elegant_cabinet_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/elegant_cabinet_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("elegant_cabinet_schematic", elegant_cabinet_schematic)