--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

fat_bottle_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/bottle_fat_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("fat_bottle_schematic", fat_bottle_schematic)