--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

feed_tube = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/feed_tubes.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("feed_tube", feed_tube)