--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

fireworks_packager = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/firework_fixer.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("fireworks_packager", fireworks_packager)