--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

firework_casing = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/firework_casing.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("firework_casing", firework_casing)