--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

gambling_table_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/gambling_table_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("gambling_table_schematic", gambling_table_schematic)