--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

goggles_s03 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/wearables/goggles/goggles_s03.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("goggles_s03", goggles_s03)