--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

gungan_signet = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/misc/gungan_signet.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("gungan_signet", gungan_signet)