--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

gungan_lance = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/misc/gungan_lance.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("gungan_lance", gungan_lance)