--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

hedon_istee_treasure_map = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/quest/treasure_map_hedon.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("hedon_istee_treasure_map", hedon_istee_treasure_map)