--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

jawa_beads = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/misc/jawa_beads.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("jawa_beads", jawa_beads)