--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

kitchen_utensils = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/utensils_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("kitchen_utensils", kitchen_utensils)