--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

krayt_dragon_scales = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/component/armor/armor_segment_enhancement_krayt.iff",
	craftingValues = {
		{"armor_special_type",0,0,0},
		{"acideffectiveness",1,6,10},
		{"heateffectiveness",1,6,10},
		{"energyeffectiveness",1,6,10},
		{"kineticeffectiveness",1,6,10},
		{"coldeffectiveness",1,6,10},
		{"blasteffectiveness",1,6,10},
		{"useCount",5,13,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("krayt_dragon_scales", krayt_dragon_scales)
