--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

locked_container = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/container/loot/player_loot_crate.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("locked_container", locked_container)