--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_dress = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Dress",
	directObjectTemplate = "object/tangible/wearables/dress/nightsister_dress.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_dress", ns_dress)