--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_hat_type_03 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Hat (type 3)",
	directObjectTemplate = " object/tangible/wearables/hat/nightsister_hat_s03.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_hat_type_03", ns_hat_type_03)