--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_hat_type_02 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Hat (Type 2)",
	directObjectTemplate = "object/tangible/wearables/hat/nightsister_hat_s02.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_hat_type_02", ns_hat_type_02)