--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_pants_type_01 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Pants (Type 1)",
	directObjectTemplate = "object/tangible/wearables/pants/nightsister_pants_s01.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_pants_type_01", ns_pants_type_01)