--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

packaged_flash_powder = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/powder_pack.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("packaged_flash_powder", packaged_flash_powder)