--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

paint_cartridge = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/paint_cartridge.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("paint_cartridge", paint_cartridge)