--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

painting_luke_wanted = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_luke_wanted.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("painting_luke_wanted", painting_luke_wanted)