--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

painting_vader_victory = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_vader_victory.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("painting_vader_victory", painting_vader_victory)