--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

paint_disperser = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/paint_disperser.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("paint_disperser", paint_disperser)