--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

painting_bw_stormtrooper = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_bw_stormtrooper.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("painting_bw_stormtrooper", painting_bw_stormtrooper)