--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

pear_bottle_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/bottle_pear_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("pear_bottle_schematic", pear_bottle_schematic)