--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

picture_printer = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/picture_printer.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("picture_printer", picture_printer)