--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

portable_stove_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/stove_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("portable_stove_schematic", portable_stove_schematic)