--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

processor_attachment = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/processor_attachments.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("processor_attachment", processor_attachment)