--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

pulverizer = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/pulverizer.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("pulverizer", pulverizer)