--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

radar_screen_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/radar_screen_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("radar_screen_schematic", radar_screen_schematic)