--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

resource_deed = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/veteran_reward/resource.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("resource_deed", resource_deed)