--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

RIS_diagram = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_armor_blueprint.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("RIS_diagram", RIS_diagram)