--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

satchel = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/container/general/satchel.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("satchel", satchel)