--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

skill_buff_rifle_accuracy = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/skill_buff/skill_buff_rifle_accuracy.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("skill_buff_rifle_accuracy", skill_buff_rifle_accuracy)