--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

skill_buff_unarmed_speed = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/skill_buff/skill_buff_unarmed_speed.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("skill_buff_unarmed_speed", skill_buff_unarmed_speed)