--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

slave_brazier_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/slave_brazier_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("slave_brazier_schematic", slave_brazier_schematic)