--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

spear_rack_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/spear_rack_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("spear_rack_schematic", spear_rack_schematic)