--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

spinner_blade = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/spinning_blade.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("spinner_blade", spinner_blade)