--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

spitting_rawl_poster = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_teras_kasi.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("spitting_rawl_poster", spitting_rawl_poster)