--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

streetlamp_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/streetlamp_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("streetlamp_schematic", streetlamp_schematic)