--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

tall_bottle_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/bottle_tall_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("tall_bottle_schematic", tall_bottle_schematic)