--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

tanned_hide_s02_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/tanning_hide_s02_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("tanned_hide_s02_schematic", tanned_hide_s02_schematic)