--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

tatooine_tapestry_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/tatooine_tapestry_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("tatooine_tapestry_schematic", tatooine_tapestry_schematic)