--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

technical_console_schematic_2 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/technical_console_s02_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("technical_console_schematic_2", technical_console_schematic_2)