--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

theme_park_loot_shipping_manifest = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "Shipping Manifest",
	directObjectTemplate = "object/tangible/mission/mission_datadisk.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("theme_park_loot_shipping_manifest", theme_park_loot_shipping_manifest)