--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

theme_park_loot_chicken_leg = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "Chicken Leg",
	directObjectTemplate = "object/tangible/food/meat_object.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("theme_park_loot_chicken_leg", theme_park_loot_chicken_leg)