--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

theme_park_loot_rocket = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "Rocket Launcher",
	directObjectTemplate = "object/tangible/loot/misc/firework_dud_s1.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("theme_park_loot_rocket", theme_park_loot_rocket)