--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

theme_park_loot_fambaa_blood = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "Jar of Fambaa Blood",
	directObjectTemplate = "object/tangible/container/jar/jar_guts_s01.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("theme_park_loot_fambaa_blood", theme_park_loot_fambaa_blood)