--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

throw_pillow_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/throwpillow_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("throw_pillow_schematic", throw_pillow_schematic)