--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

tumble_blender_schematic = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/loot_schematic/tumble_blender_schematic.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("tumble_blender_schematic", tumble_blender_schematic)