--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ubese_armor_bandolier = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Ubese Armor Bandolier",
	directObjectTemplate = "object/tangible/wearables/armor/ubese/armor_ubese_bandolier.iff",
	craftingValues = {
		{"armor_integrity",18750,31250,0},
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ubese_armor_bandolier", ubese_armor_bandolier)