--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

valley_view_painting = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/painting/painting_valley_view.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("valley_view_painting", valley_view_painting)