--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

viewscreen_reader = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/loot/simple_kit/viewscreen_reader.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("viewscreen_reader", viewscreen_reader)