--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

armor_marauder_bracer_r = {
	minimumLevel = 0,
	maximumLevel = 0,
	customObjectName = "",
	directObjectTemplate = "object/tangible/wearables/armor/marauder/armor_marauder_s02_bracer_r.iff",
	craftingValues = {
		{"armor_integrity",35000,35000,0},
		{"armor_rating",1,1,0},
		{"armor_effectiveness",45,45,0},
		{"kineticeffectiveness",0,0,0},
		{"heateffectiveness",0,0,0},
		{"coldeffectiveness",0,0,0},
		{"acideffectiveness",0,0,0},
		{"electrictyeffectiveness",0,0,0},
		{"stuneffectiveness",0,0,0},
		{"armor_health_encumbrance",1,1,0},
		{"armor_action_encumbrance",1,1,0},
		{"armor_mind_encumbrance",1,1,0},
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("armor_marauder_bracer_r", armor_marauder_bracer_r)