--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

mabari_armor_leggings_quest = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/wearables/armor/zam/armor_zam_wesell_pants_quest.iff",
	craftingValues = {
		{"armor_integrity",15000,15000,0},
		{"armor_rating",1,1,0},
		{"armor_effectiveness",45,45,10},
		{"heateffectiveness",45,45,10},
		{"blasteffectiveness",45,45,10},
		{"armor_health_encumbrance",1,1,0},
		{"armor_action_encumbrance",1,1,0},
		{"armor_mind_encumbrance",1,1,0},
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {
		{"dizzy_defense",5},
		{"ranged_defense",3}
	}
}

addLootItemTemplate("mabari_armor_leggings_quest", mabari_armor_leggings_quest)