--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

janta_hides = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/component/armor/armor_segment_enhancement_janta.iff",
	craftingValues = {
		{"armor_special_type",0,0,0},
		{"armor_effectiveness",3,6,10},
		{"hitpoints",0,0,0,0},
		{"useCount",5,13,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("janta_hides", janta_hides)
