--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

nightsister_layer = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/component/armor/armor_layer_nightsister.iff",
	craftingValues = {
		{"armor_special_type",0,0,0},
		{"armor_effectiveness",2,5,10},
		{"armor_action_encumbrance",-2,-6,0},
		{"useCount",5,13,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("nightsister_layer", nightsister_layer)
