--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

bloodrazor_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "flora_recycler_schematic", weight = 10000000}
	}
}

addLootGroupTemplate("bloodrazor_common", bloodrazor_common)