--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

canyon_corsair_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "agitator_motor_schematic", weight = 5000000},
		{itemTemplate = "metal_recycler_schematic", weight = 1500000},
		{itemTemplate = "skill_buff_rifle_accuracy", weight = 1000000},
		{itemTemplate = "skill_buff_rifle_speed", weight = 1000000},
		{itemTemplate = "small_motor", weight = 1500000}
	}
}

addLootGroupTemplate("canyon_corsair_common", canyon_corsair_common)