--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

chunker_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "processor_attachment", weight = 480000},
		{itemTemplate = "pulverizer", weight = 5710000},
		{itemTemplate = "red_wiring", weight = 3810000}
	}
}

addLootGroupTemplate("chunker_common", chunker_common)