--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

crystals_premium = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "goggles_s01", weight = 1000000},
		{itemTemplate = "goggles_s02", weight = 1000000},
		{itemTemplate = "goggles_s03", weight = 1000000},
		{itemTemplate = "goggles_s04", weight = 1000000},
		{itemTemplate = "goggles_s05", weight = 1000000}
	}
}

addLootGroupTemplate("crystals_premium", crystals_premium)