--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

darth_vader = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
	}
}

addLootGroupTemplate("darth_vader", darth_vader)