--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

gungan_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = -1,
	lootItems = {
		{itemTemplate = "gungan_lance", weight = 5000000},
		{itemTemplate = "gungan_signet", weight = 5000000}
	}
}

addLootGroupTemplate("gungan_common", gungan_common)