--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

hidden_dagger_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "skill_buff_carbine_accuracy", weight = 3333333},
		{itemTemplate = "skill_buff_carbine_speed", weight = 3333333},
		{itemTemplate = "spinner_blade", weight = 3333334}
	}
}

addLootGroupTemplate("hidden_dagger_common", hidden_dagger_common)