--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

imperial_officer_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "couch_blue_schematic", weight = 3333334},
		{itemTemplate = "technical_console_schematic_1", weight = 3333333},
		{itemTemplate = "technical_console_schematic_2", weight = 3333333}
	}
}

addLootGroupTemplate("imperial_officer_common", imperial_officer_common)