--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

janta_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "janta_blood", weight = 3000000},
		{itemTemplate = "knife_janta", weight = 4250000},
		{itemTemplate = "janta_hides", weight = 2750000}
	}
}

addLootGroupTemplate("janta_common", janta_common)
