--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

jawa_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = -1,
	lootItems = {
		{itemTemplate = "jawa_beads", weight = 10000000}
	}
}

addLootGroupTemplate("jawa_common", jawa_common)