--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

mauler_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "portable_stove_schematic", weight = 3333334},
		{itemTemplate = "skill_buff_onehandmelee_accuracy", weight = 3333333},
		{itemTemplate = "skill_buff_onehandmelee_speed", weight = 3333333}
	}
}

addLootGroupTemplate("mauler_common", mauler_common)