--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

melee_blacksun_razor = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "black_sun_razor", weight = 10000000}
	}
}

addLootGroupTemplate("melee_blacksun_razor", melee_blacksun_razor)
