--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

nyax = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "nyax_necklace", weight = 5000000},
		{itemTemplate = "nyax_sword", weight = 5000000}
	}
}

addLootGroupTemplate("nyax", nyax)
