--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

plasma_thief_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "kitchen_utensils", weight = 10000000}
	}
}

addLootGroupTemplate("plasma_thief_common", plasma_thief_common)