--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

resource_deed = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "resource_deed", weight = 10000000}
	}
}

addLootGroupTemplate("resource_deed", resource_deed)