--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

skaak_tipper_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "kitchen_utensils", weight = 10000000}
	}
}

addLootGroupTemplate("skaak_tipper_common", skaak_tipper_common)