--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_armor = {
	description = "",
	minimumLevel = 0,
	maximumLevel = -1,
	lootItems = {
		{itemTemplate = "smc_bicep_l", weight = 2500000},
		{itemTemplate = "smc_bicep_r", weight = 2500000},
		{itemTemplate = "smc_bracer_l", weight = 2500000},
		{itemTemplate = "smc_bracer_r", weight = 2500000}
	}
}

addLootGroupTemplate("smc_armor", smc_armor)