--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_clothing = {
	description = "",
	minimumLevel = 0,
	maximumLevel = -1,
	lootItems = {
		{itemTemplate = "smc_boots", weight = 1250000},
		{itemTemplate = "smc_hat_type_01", weight = 1250000},
		{itemTemplate = "smc_hat_type_02", weight = 1250000},
		{itemTemplate = "smc_mask", weight = 1250000},
		{itemTemplate = "smc_pack", weight = 1250000},
		{itemTemplate = "smc_shirt_type_01", weight = 1250000},
		{itemTemplate = "smc_shirt_type_02", weight = 1250000},
		{itemTemplate = "smc_shirt_type_03", weight = 1250000}
	}
}

addLootGroupTemplate("smc_clothing", smc_clothing)