--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

task_reward_hedon_istee = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "hedon_istee_treasure_map", weight = 10000000}
	}
}

addLootGroupTemplate("task_reward_hedon_istee", task_reward_hedon_istee)