--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

theme_park_loot_rocket = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "theme_park_loot_rocket", weight = 10000000}
	}
}

addLootGroupTemplate("theme_park_loot_rocket", theme_park_loot_rocket)