--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

theme_park_reward_imperial_thrawn_suits = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "atat_suit", weight = 5000000},
		{itemTemplate = "tie_suit", weight = 5000000}
	}
}

addLootGroupTemplate("theme_park_reward_imperial_thrawn_suits", theme_park_reward_imperial_thrawn_suits)