--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

theme_park_reward_imperial_thrawn_helmets = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "atat_helmet", weight = 5000000},
		{itemTemplate = "tie_helmet", weight = 5000000}
	}
}

addLootGroupTemplate("theme_park_reward_imperial_thrawn_helmets", theme_park_reward_imperial_thrawn_helmets)