--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

valarian_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "party_poster", weight = 2500000},
		{itemTemplate = "skill_buff_carbine_accuracy", weight = 2500000},
		{itemTemplate = "skill_buff_carbine_speed", weight = 2500000},
		{itemTemplate = "valley_view_painting", weight = 2500000}
	}
}

addLootGroupTemplate("valarian_common", valarian_common)