--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

weequay_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "elegant_cabinet_schematic", weight = 10000000}
	}
}

addLootGroupTemplate("weequay_common", weequay_common)