--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

brackaset_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
--		{itemTemplate = "brackaset_plates", weight = 5000000},
		{itemTemplate = "krayt_composite_segment", weight = 10000000}
	}
}

addLootGroupTemplate("brackaset_common", brackaset_common)
