--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

fambaa_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "krayt_composite_segment", weight = 10000000}
--		{itemTemplate = "fambaa_plates", weight = 5000000}
	}
}

addLootGroupTemplate("fambaa_common", fambaa_common)
