--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

kliknik_common = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "krayt_composite_segment", weight = 5000000},
		{itemTemplate = "kliknik_gland", weight = 5000000}
	}
}

addLootGroupTemplate("kliknik_common", kliknik_common)
