--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

krayt_dragon_common2 = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
--		{itemTemplate = "krayt_composite_segment", weight = 3333334},
		{itemTemplate = "krayt_dragon_scales", weight = 5000000},
		{itemTemplate = "krayt_dragon_tissue_common", weight = 5000000}
	}
}

addLootGroupTemplate("krayt_dragon_common2", krayt_dragon_common2)
