stuee = Creature:new {
	objectName = "",
	customName = "Stuee Walshaw",
	socialGroup = "rebel",
	pvpFaction = "rebel",
	faction = "rebel",
	level = 400,
	chanceHit = 100,
	damageMin = 2000,
	damageMax = 5000,
	baseXp = 500000,
	baseHAM = 5000000,
	baseHAMmax = 10000000,
	armor = 3,
	resists = {99,99,99,99,99,99,99,99,99},
	meatType = "",
	meatAmount = 0,
	hideType = "",
	hideAmount = 0,
	boneType = "",
	boneAmount = 0,
	milk = 0,
	tamingChance = 0,
	ferocity = 50,
	pvpBitmask = NONE,
	creatureBitmask = PACK,
	optionsBitmask = 264,
	diet = CARNIVORE,

	templates = {"object/mobile/dressed_sith_shadow_hum_m_01.iff",
		"object/mobile/dressed_sith_shadow_hum_m_02.iff",
		"object/mobile/dressed_sith_shadow_hum_m_03.iff"},
	lootGroups = {},
	weapons = {},
	conversationTemplate = "",
	attacks = merge(lightsabermaster,forcepowermaster)
}

CreatureTemplates:addCreatureTemplate(stuee, "stuee")
