-- includeFile("building/player/tobin_house.lua")
includeFile("building/player/idhouses/musty_house.lua")
includeFile("building/player/idhouses/jedi_house.lua")
includeFile("building/player/idhouses/vipbunker_house.lua")

includeFile("building/player/idhouses/atat_house.lua")
includeFile("building/player/idhouses/bespin_house.lua")
includeFile("building/player/idhouses/commando_house.lua")
includeFile("building/player/idhouses/emperors_house.lua")
includeFile("building/player/idhouses/hangar_house.lua")
includeFile("building/player/idhouses/jabbas_house.lua")
includeFile("building/player/idhouses/ns_hut_house.lua")
includeFile("building/player/idhouses/rebel_house.lua")
includeFile("building/player/idhouses/relaxation_house.lua")
includeFile("building/player/idhouses/sandcrawler_house.lua")
includeFile("building/player/idhouses/sith_house.lua")
includeFile("building/player/idhouses/sm_hut_house.lua")
includeFile("building/player/idhouses/tree_house.lua")
includeFile("building/player/idhouses/vehicle_house.lua")
includeFile("building/player/idhouses/yoda_house.lua")
includeFile("building/player/idhouses/yt1300_house.lua")
includeFile("building/player/idhouses/gen_large_win_01.lua")
includeFile("building/player/idhouses/gen_large_win_02.lua")
includeFile("building/player/idhouses/gen_medium_win_01.lua")
includeFile("building/player/idhouses/gen_medium_win_02.lua")
includeFile("building/player/idhouses/gen_small_win_01.lua")
includeFile("building/player/idhouses/gen_small_win_02.lua")
includeFile("building/player/idhouses/nab_small_win_01.lua")
includeFile("building/player/idhouses/tat_small_win_01.lua")


