--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

rancor_hides = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/component/armor/armor_segment_enhancement_rancor.iff",
	craftingValues = {
		{"armor_special_type",0,0,0},
		{"armor_effectiveness",2,7,10},
		{"armor_integrity",1500,3000,0},		
		{"heateffectiveness",3,9,10},
		{"coldeffectiveness",3,9,10},
		{"armor_health_encumbrance",4,0,0},
		{"armor_action_encumbrance",4,0,0},
		{"armor_mind_encumbrance",4,0,0},
		{"useCount",5,13,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("rancor_hides", rancor_hides)
