--jedi house deed
object_tangible_deed_player_house_deed_shared_jedi_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_jedi_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_jedi_house_deed, "object/tangible/deed/player_house_deed/shared_jedi_house_deed.iff")

--vipbunker deed
object_tangible_deed_player_house_deed_shared_vipbunker_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_vipbunker_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_vipbunker_house_deed, "object/tangible/deed/player_house_deed/shared_vipbunker_house_deed.iff")

--musty house deed
object_tangible_deed_player_house_deed_shared_musty_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_musty_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_musty_house_deed, "object/tangible/deed/player_house_deed/shared_musty_house_deed.iff")

--atat house deed
object_tangible_deed_player_house_deed_shared_atat_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_atat_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_atat_house_deed, "object/tangible/deed/player_house_deed/shared_atat_house_deed.iff")

--bespin house deed
object_tangible_deed_player_house_deed_shared_bespin_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_bespin_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_bespin_house_deed, "object/tangible/deed/player_house_deed/shared_bespin_house_deed.iff")

--commando house deed
object_tangible_deed_player_house_deed_shared_commando_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_commando_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_commando_house_deed, "object/tangible/deed/player_house_deed/shared_commando_house_deed.iff")

--emperors house deed
object_tangible_deed_player_house_deed_shared_emperors_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_emperors_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_emperors_house_deed, "object/tangible/deed/player_house_deed/shared_emperors_house_deed.iff")

--generic_large_window_s01 house deed
object_tangible_deed_player_house_deed_shared_generic_large_window_s01_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_generic_large_window_s01_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_generic_large_window_s01_deed, "object/tangible/deed/player_house_deed/shared_generic_large_window_s01_deed.iff")

--generic_large_window_s02 house deed
object_tangible_deed_player_house_deed_shared_generic_large_window_s02_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_generic_large_window_s02_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_generic_large_window_s02_deed, "object/tangible/deed/player_house_deed/shared_generic_large_window_s02_deed.iff")

--generic_medium_window_s01 house deed
object_tangible_deed_player_house_deed_shared_generic_medium_window_s01_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_generic_medium_window_s01_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_generic_medium_window_s01_deed, "object/tangible/deed/player_house_deed/shared_generic_medium_window_s01_deed.iff")

--generic_medium_window_s02 house deed
object_tangible_deed_player_house_deed_shared_generic_medium_window_s02_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_generic_medium_window_s02_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_generic_medium_window_s02_deed, "object/tangible/deed/player_house_deed/shared_generic_medium_window_s02_deed.iff")

--generic_small_window_s01 house deed
object_tangible_deed_player_house_deed_shared_generic_small_window_s01_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_generic_small_window_s01_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_generic_small_window_s01_deed, "object/tangible/deed/player_house_deed/shared_generic_small_window_s01_deed.iff")

--generic_small_medium_s02 house deed
object_tangible_deed_player_house_deed_shared_generic_small_window_s02_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_generic_small_window_s02_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_generic_small_window_s02_deed, "object/tangible/deed/player_house_deed/shared_generic_small_window_s02_deed.iff")

--hangar deed
object_tangible_deed_player_house_deed_shared_hangar_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_hangar_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_hangar_house_deed, "object/tangible/deed/player_house_deed/shared_hangar_house_deed.iff")

--jabbas deed
object_tangible_deed_player_house_deed_shared_jabbas_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_jabbas_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_jabbas_house_deed, "object/tangible/deed/player_house_deed/shared_jabbas_house_deed.iff")

--naboo_small_window_s01 house deed
object_tangible_deed_player_house_deed_shared_naboo_small_window_s01_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_naboo_small_window_s01_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_naboo_small_window_s01_deed, "object/tangible/deed/player_house_deed/shared_naboo_small_window_s01_deed.iff")

--ns_hut deed
object_tangible_deed_player_house_deed_shared_ns_hut_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_ns_hut_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_ns_hut_house_deed, "object/tangible/deed/player_house_deed/shared_ns_hut_deed.iff")

--rebel deed
object_tangible_deed_player_house_deed_shared_rebel_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_rebel_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_rebel_house_deed, "object/tangible/deed/player_house_deed/shared_rebel_house_deed.iff")

--relaxation deed
object_tangible_deed_player_house_deed_shared_relaxation_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_relaxation_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_relaxation_house_deed, "object/tangible/deed/player_house_deed/shared_relaxation_house_deed.iff")

--sandcrawler deed
object_tangible_deed_player_house_deed_shared_sandcrawler_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_sandcrawler_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_sandcrawler_house_deed, "object/tangible/deed/player_house_deed/shared_sandcrawler_house_deed.iff")

--sith deed
object_tangible_deed_player_house_deed_shared_sith_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_sith_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_sith_house_deed, "object/tangible/deed/player_house_deed/shared_sith_house_deed.iff")

--sm_hut deed
object_tangible_deed_player_house_deed_shared_sm_hut_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_sm_hut_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_sm_hut_house_deed, "object/tangible/deed/player_house_deed/shared_sm_hut_deed.iff")

--tatooine_small_window_s01 house deed
object_tangible_deed_player_house_deed_shared_tatooine_small_window_s01_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_tatooine_small_window_s01_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_tatooine_small_window_s01_deed, "object/tangible/deed/player_house_deed/shared_tatooine_small_window_s01_deed.iff")

--tree deed
object_tangible_deed_player_house_deed_shared_tree_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_tree_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_tree_house_deed, "object/tangible/deed/player_house_deed/shared_tree_house_deed.iff")

--vehicle deed
object_tangible_deed_player_house_deed_shared_vehicle_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_vehicle_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_vehicle_house_deed, "object/tangible/deed/player_house_deed/shared_vehicle_house_deed.iff")

--yoda deed
object_tangible_deed_player_house_deed_shared_yoda_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_yoda_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_yoda_house_deed, "object/tangible/deed/player_house_deed/shared_yoda_house_deed.iff")

--yt1300 deed
object_tangible_deed_player_house_deed_shared_yt1300_house_deed = SharedTangibleObjectTemplate:new {
	clientTemplateFileName = "object/tangible/deed/player_house_deed/shared_yt1300_house_deed.iff"
}
ObjectTemplates:addClientTemplate(object_tangible_deed_player_house_deed_shared_yt1300_house_deed, "object/tangible/deed/player_house_deed/shared_yt1300_house_deed.iff")
