--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

geo_power_cube_yellow = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/component/weapon/geonosian_power_cube_yellow.iff",
	craftingValues = {
		{"armor_effectiveness",3,8,10},
		{"useCount",5,13,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("geo_power_cube_yellow", geo_power_cube_yellow)
