-- Generated by LairTool
yavin4_black_sun = Lair:new {
	mobiles = {{"black_sun_guard_02", 0},{"black_sun_assassin_02", 0}},
	spawnLimit = 15,
	buildingsVeryEasy = {"object/tangible/lair/base/lair_base_hovel.iff"},
	buildingsEasy = {"object/tangible/lair/base/lair_base_hovel.iff"},
	buildingsMedium = {"object/tangible/lair/base/lair_base_hovel.iff"},
	buildingsHard = {"object/tangible/lair/base/lair_base_hovel.iff"},
	buildingsVeryHard = {"object/tangible/lair/base/lair_base_hovel.iff"},
}	lairType = "npc"

addLairTemplate("yavin4_black_sun", yavin4_black_sun)

