--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

bh_armor_bicep_l = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/wearables/armor/bounty_hunter/armor_bounty_hunter_bicep_l.iff",
	craftingValues = {
		{"armor_integrity",35000,35000,0},
		{"armor_rating",1,1,0},
		{"armor_effectiveness",55,55,0},
--		{"energyeffectiveness",60,60},
--		{"heateffectiveness",60,60,0},
--		{"coldeffectiveness",-35,-35,0},
--		{"acideffectiveness",60,60,0},
--		{"electrictyeffectiveness",60,60,0},
--		{"stuneffectiveness",60,60,0},
		{"armor_health_encumbrance",1,1,0},
		{"armor_action_encumbrance",1,1,0},
		{"armor_mind_encumbrance",1,1,0},
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("bh_armor_bicep_l", bh_armor_bicep_l)