--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

bh_armor_boots = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "",
	directObjectTemplate = "object/tangible/wearables/armor/bounty_hunter/armor_bounty_hunter_boots.iff",
	craftingValues = {
		{"armor_integrity",35000,35000,0},
		{"armor_rating",1,1,0},
		{"armor_effectiveness",55,55,0},
--		{"kineticeffectiveness",0,0,0},
--		{"heateffectiveness",0,0,0},
--		{"coldeffectiveness",0,0,0},
--		{"acideffectiveness",0,0,0},
--		{"electrictyeffectiveness",0,0,0},
--		{"stuneffectiveness",0,0,0},
		{"armor_health_encumbrance",1,1,0},
		{"armor_action_encumbrance",1,1,0},
		{"armor_mind_encumbrance",1,1,0},
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("bh_armor_boots", bh_armor_boots)