--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

icav_comp_kin = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Komrk Kinetic Armor Segment",
	directObjectTemplate = "object/tangible/component/armor/armor_segment_composite_krayt.iff",
	craftingValues = {
		{"armor_special_type",0,0,0},
		{"armor_effectiveness",24,24,10},
		{"kineticeffectiveness",38,38,10},
		{"armor_integrity",1325,1325,0},
		{"armor_action_encumbrance",52,52,0},
		{"armor_health_encumbrance",52,52,0},
		{"armor_mind_encumbrance",54,54,0},
		{"useCount",1000,1000,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("icav_comp_kin", icav_comp_kin)
