--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

icav_comp_nrg = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Komrk NRG Armor Segment",
	directObjectTemplate = "object/tangible/component/armor/armor_segment_composite_krayt.iff",
	craftingValues = {
		{"armor_special_type",0,0,0},
		{"armor_effectiveness",25,25,10},
		{"energyeffectiveness",37,37,10},
		{"armor_integrity",1438,1438,0},
		{"armor_action_encumbrance",48,48,0},
		{"armor_health_encumbrance",48,48,0},
		{"armor_mind_encumbrance",50,50,0},
		{"useCount",1000,1000,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("icav_comp_nrg", icav_comp_nrg)
