--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

icav_comp_cold = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Komrk Cold Armor Segment",
	directObjectTemplate = "object/tangible/component/armor/armor_segment_composite_krayt.iff",
	craftingValues = {
		{"armor_special_type",0,0,0},
		{"armor_effectiveness",26,26,10},
		{"coldeffectiveness",10,10,10},
		{"armor_integrity",2563,2563,0},
		{"armor_action_encumbrance",25,26,0},
		{"armor_health_encumbrance",26,26,0},
		{"armor_mind_encumbrance",28,28,0},
		{"useCount",1000,1000,0},
	},
	customizationStringNames = {},
	customizationValues = {}
}

addLootItemTemplate("icav_comp_cold", icav_comp_cold)
