--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_boots = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Boots",
	directObjectTemplate = "object/tangible/wearables/boots/nightsister_boots.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_boots", ns_boots)