--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_pants_type_02 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Pants (Type 2)",
	directObjectTemplate = "object/tangible/wearables/pants/nightsister_pants_s02.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_pants_type_02", ns_pants_type_02)