--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_shirt_type_03 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Shirt (Type 3)",
	directObjectTemplate = " object/tangible/wearables/shirt/nightsister_shirt_s03.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_shirt_type_03", ns_shirt_type_03)