--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_shirt_type_01 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Nightsister Shirt (Type 1)",
	directObjectTemplate = "object/tangible/wearables/shirt/nightsister_shirt_s01.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("ns_shirt_type_01", ns_shirt_type_01)