--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

redeemable_voucher = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "One (1) Free Crate of Resources",
	directObjectTemplate = "object/tangible/veteran_reward/resource.iff",
	craftingValues = {},
	customizationStringNames = {},
	customizationValues = {},
	junkDealerTypeNeeded = JUNKGENERIC,
	junkMinValue = 20,
	junkMaxValue = 40
}

addLootItemTemplate("redeemable_voucher", redeemable_voucher)
