--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

resource_deed = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Redeemable for one(1) Crate of Free Resources",
	directObjectTemplate = "object/tangible/loot/misc/ticket_expired.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
}

addLootItemTemplate("resource_deed", resource_deed)
