--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_bracer_l = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Singing Mountain Clan Bracer (Left)",
	directObjectTemplate = "object/tangible/wearables/armor/singing_mountain_clan/armor_smc_s01_bracer_l.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("smc_bracer_l", smc_bracer_l)