--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_mask = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Singing Mountain Clan Mask",
	directObjectTemplate = "object/tangible/wearables/hat/singing_mountain_clan_mask_s01.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("smc_mask", smc_mask)