--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_boots = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Singing Mountain Clan Boots",
	directObjectTemplate = "object/tangible/wearables/boots/singing_mountain_clan_boots.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("smc_boots", smc_boots)