--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_hat_type_02 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Singing Mountain Clan Hat (Type 2)",
	directObjectTemplate = "object/tangible/wearables/hat/singing_mountain_clan_hat_s02.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("smc_hat_type_02", smc_hat_type_02)