--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_shirt_type_03 = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Singing Mountain Clan Shirt (Type 3)",
	directObjectTemplate = "object/tangible/wearables/shirt/singing_mountain_clan_shirt_s03.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("smc_shirt_type_03", smc_shirt_type_03)