--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_bicep_r = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Singing Mountain Clan Bicep (Right)",
	directObjectTemplate = "object/tangible/wearables/armor/singing_mountain_clan/armor_smc_s01_bicep_r.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("smc_bicep_r", smc_bicep_r)