--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

smc_pack = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Singing Mountain Clan Backpack",
	directObjectTemplate = "object/tangible/wearables/backpack/singing_mountain_clan_backpack.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("smc_pack", smc_pack)