--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

tarkin_award = {
	minimumLevel = 0,
	maximumLevel = -1,
	customObjectName = "Tarkin Award for Outstanding Work",
	directObjectTemplate = "object/tangible/loot/misc/palm_frond.iff",
	craftingValues = {
	},
	customizationStringNames = {},
	customizationValues = {},
	skillMods = {

	}
}

addLootItemTemplate("tarkin_award", tarkin_award)
