--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

comp_cold = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "icav_comp_cold", weight = 10000000}
--		{itemTemplate = "fambaa_plates", weight = 5000000}
	}
}

addLootGroupTemplate("comp_cold", comp_cold)
