--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

comp_kin = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "icav_comp_kin", weight = 10000000}
--		{itemTemplate = "fambaa_plates", weight = 5000000}
	}
}

addLootGroupTemplate("comp_kin", comp_kin)
