--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

deed_voucher = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "redeemable_voucher", weight = 10000000}
	}
}

addLootGroupTemplate("deed_voucher", deed_voucher)
