--Automatically generated by SWGEmu Spawn Tool v0.12 loot editor.

ns_clothing = {
	description = "",
	minimumLevel = 0,
	maximumLevel = 0,
	lootItems = {
		{itemTemplate = "ns_boots", weight = 1000000},
		{itemTemplate = "ns_dress", weight = 1000000},
		{itemTemplate = "ns_hat_type_01", weight = 1000000},
		{itemTemplate = "ns_hat_type_02", weight = 1000000},
		{itemTemplate = "ns_hat_type_03", weight = 1000000},
		{itemTemplate = "ns_pants_type_01", weight = 1000000},
		{itemTemplate = "ns_pants_type_02", weight = 1000000},
		{itemTemplate = "ns_shirt_type_01", weight = 1000000},
		{itemTemplate = "ns_shirt_type_02", weight = 1000000},
		{itemTemplate = "ns_shirt_type_03", weight = 1000000}
	}
}

addLootGroupTemplate("ns_clothing", ns_clothing)